apiVersion: v1
kind: Service
metadata:
  name: ingredients
  namespace: woodpantry
  labels:
    app: ingredients
spec:
  selector:
    app: ingredients
  ports:
    - port: 80
      targetPort: 8080
